grafana:
  adminUser: admin
  adminPassword: admin123
  service:
    type: ClusterIP
  persistence:
    enabled: false

prometheus:
  prometheusSpec:
    retention: 2d
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    scrapeInterval: 60s
    kubeletService: kubelet
    scrapeKubelet: true
    enableKubeletMetrics: true
